# Generated by Django 3.1 on 2023-07-28 06:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wears', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='femalewear',
            old_name='bImage',
            new_name='wImage',
        ),
        migrations.RenameField(
            model_name='malewear',
            old_name='pImage',
            new_name='mImage',
        ),
        migrations.RemoveField(
            model_name='footwear',
            name='bImage',
        ),
        migrations.AddField(
            model_name='footwear',
            name='fImage',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
