# Generated by Django 3.1 on 2023-07-28 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wears', '0002_auto_20230728_0713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footwear',
            name='fImage',
            field=models.URLField(null=True),
        ),
    ]
